### ISSUE TITLE
License

### ISSUE THREAD

**Issue by sungwoncho** [dnote/cli#146]
I would like to propose a change of license for this project. When Dnote started out as a simple 300-line program about 2 years back, an academic license such as MIT license worked fine. However, now that we have grown to more than 10 contributors, it is essential to move to another permissive or a reciprocal license.

* I believe that the IP assignment of contribution is important for the long term success of this project. By not creating a complicated chain of ownership, Dnote can stay as a free/libre software while moving fast as a business. For this we could use permissive licenses such as **Apache 2.0**.
* I would be more comfortable with the trademark protection and patent clause for Dnote provided by **Apache 2.0** to continue evolving Dnote in the years to come with more contributors.
* We might need a CLA as the number of contributors grows to avoid creating a complicated chain of ownership.
* As in #139, I plan to open source the server side code and make the whole Dnote system a free/libre software. The server side is going to be licensed under AGPL. And as author of Dnote I truly care about sharing. Therefore I also think that a reciprocal license such as **GPLv3** is a good option for CLI.

## Next action

We have [14 contributors](https://github.com/dnote/cli/graphs/contributors) at the moment.

* What are your thought about this proposal?
* Would you sign a contributor license agreement (CLA)?

I have been enjoying maintaining this project for the past two years and and would like it to be a success in the years to come. Your feedback and help will be appreciated.

@michielboekhoff @klebervirgilio @martaccmoreno @maml @nakabonne @rkuska @apostov @FearNotDaniel @im-kulikov @newyork-anthonyng @liamjack @girish3 @Erwyn 

- Sung

**Comment by sungwoncho** [comment]
Due to the absense of response and long wait, I have decided to go ahead with the change. I have taken the following steps:

## all contributions

The following are all external contributions and how they stand in terms of the license change. All contributions, except a7e7364332d1d93e05739a9b76ec562a2d8e478e, are no longer used in the current release due to the recent rewrite of sync and migration of note storage from JSON to SQLite.

- [x] 477e625de4551776a5c419bb0c9340b9845d61ed by Erwyn (fix a typo in README) - reverted
- [x] 9d6334c9d732f844ee906f802749235904147682 by girish3 (no longer in use)
- [x] a0e7fd2e09d1480b84de27ef7691bd6424275250 by liamjack (no longer in use)
- [x] fd655f2cc480e3893561dd3376f8e86d0371f3ff by newyork-anthonyng (simple typo fix) - reverted
- [x] b1386722a920f2e76860806b0839781e29338f9c by im-kulikov (code cleanup) - reverted
- [x] a7e7364332d1d93e05739a9b76ec562a2d8e478e by FearNotDaniel (windows color fix)
  - [x] It was replaced by 1914f311e86483b69dc4a5ab800fc42c9e829ed3 which was independently developed at the same time the contribution was made.
- [x] 4d25b843634307ce139001bef8b757f5f50b8598 by apostov (fix lint from gometalinter) - reverted
- [x] a5ae890b9652477802f5b698b7e588229530932c by rkuska (add neovim support)
  - [x] replaced with different implemenation
- [x] e8acad1f875b81364c58f0e69dd294fcb885c322 by nakabonne (add example to README) - reverted
- [x] 0fa913382253995bcdc3ebbb5c3b03170347bfe1 by maml (fix a typo in help) - reverted
- [x] 0f13829209a3b48bd6ae710d47d4f5200bbde234 by klebervirgilio (fix output)
  - [x] replaced with different implemenation
- [x] a8702062fe701446bf7ae5765164bb211a20efa0 by martaccmoreno (fix typo in help) - reverted

- [x] c0cd9f309621a31e4c1efc07ed5f4f8065817d43 by michielboekhoff (no longer in use)
- [x] 4d45eec682401f42389c2285f732fa451200febb by michielboekhoff (no longer in use)
- [x] 2409b1d39d1445aefa58a912b6701425387829ee by michielboekhoff (no longer in use)
- [x] f95098f16d4bdb2c2624242ade4d5a4c48946e69 by michielboekhoff (no longer in use)
- [x] 941aafc9622b0a3e46b7bcc2597809dd61ccc2de by michielboekhoff (no longer in use)
- [x] 42f8de204cbabd9adab8ecfc595e53f7209364e6 by michielboekhoff (no longer in use)
- [x] 42f8de204cbabd9adab8ecfc595e53f7209364e6 by michielboekhoff (no longer in use)
- [x] 5bde1d0c0d0d417d31ec9147bb5758ad5225da94 by michielboekhoff (travis configuration)
  - [x] reconfigured travis

The changes are in [license branch](https://github.com/dnote/cli/tree/license). All future releases will be under GPLv3. The current and all past releases will be under MIT perpetually.

**Comment by sungwoncho** [comment]
@im-kulikov thanks. To be clear, the plan is to switch to a copyleft license such as GPL. This program will always be open source and free.

**Comment by im-kulikov** [comment]
@sungwoncho great... GPL is nice too

**Comment by im-kulikov** [comment]
@sungwoncho can you place full text of license in repo?

**Comment by sungwoncho** [comment]
@im-kulikov sure, fixed by #162
